dist: xenial
jobs:
  - language: go
    go: 1.15.x
    script:
    - gem -v
    - echo "Installing license finder ..."
    - gem install license_finder
    - echo "Finding Licenses"
    - license_finder action_items --enable-package-managers gomodules

  - language: ruby
    rvm: "2.3.3"
    script:
    - gem -v
    - echo "Installing license finder ..."
    - gem install license_finder
    - echo "Finding Licenses"
    - license_finder action_items --enabled-package-managers npm