dist: xenial
jobs:
  - language: go
    go: 1.15.x
    script:
    - go list
    - gem -v
    - echo "Installing license finder ..."
    - gem install license_finder
    - echo "Finding Licenses"
#     - license_finder --enabled-package-managers gomodules || true
    - license_finder report --format csv --columns=name version licenses approved --enabled-package-managers gomodules > license.csv
    - sed -i '1d' license.csv
    - column -s, -t < license.csv | less -#2 -N -S\n

  - language: ruby
    rvm: "2.3.3"
    script:
    - npm install
    - npm i -g tty-table 
    - gem -v
    - echo "Installing license finder ..."
    - gem install license_finder
    - echo "Finding Licenses"
#     - license_finder action_items --enabled-package-managers npm || true
    - license_finder report --format csv --columns=name version licenses approved --enabled-package-managers npm > license.csv
    - cat license.csv | tty-table
