dist: xenial
jobs:
  - language: go
    go: 1.15.x
    script:
    - go list
    - gem -v
    - echo "Installing license finder ..."
    - gem install license_finder
    - echo "Finding Licenses"
    - license_finder --enabled-package-managers gomodules || true

  - language: ruby
    rvm: "2.3.3"
    script:
    - npm install
    - gem -v
    - echo "Installing license finder ..."
    - gem install license_finder
    - echo "Finding Licenses"
    - license_finder action_items --enabled-package-managers npm || true
