dist: xenial
jobs:
  - language: ruby
    rvm: "2.3.3"
    script:
    - gem -v
    - echo "Installing license finder ..."
    - gem install license_finder
    - echo "Finding Licenses"
    - license_finder 