name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REPO: ${{ github.repository }}
  BUILD_BRANCH: ${{ github.ref }}
  BUILD_COMMIT: ${{ github.sha }}
  BUILD_RUNID: ${{ github.run_id }}
  CI_ENDPOINT_HOSTNAME: $GITHUB_SERVER_URL
  PULL_REQUEST_NUMBER: ${{ github.event.number }}
  
  
  
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set current date as env variable
      id: startedAt
      run: echo "::set-output name=startedAt::$(date +%s)"
  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Print Custom Env Variables
      run: |
       echo $REPO
       echo $GITHUB_HEAD_REF
       echo $BUILD_COMMIT
       echo $GITHUB_SERVER_URL 
       echo $BUILD_RUNID
       echo $PULL_REQUEST_NUMBER
       echo $GITHUB_EVENT_NAME
    - name: Post Build Success to DI
      if: ${{ success() }}
      run: |
       # Built At time 
       echo Built At :: $(date --utc +%FT%T.%3NZ)
       # status of the build
       status=Passed
       echo $status
       startedTime=${{ steps.startedAt.outputs.startedAt }}
       echo started :: $startedTime
       endTime=$(date +%s)
       echo end :: $endTime
       ELAPSED=$((endTime-startedTime))
       # Duration of the time
       echo $ELAPSED
       echo $(($ELAPSED/60))m $(($ELAPSED%60))s
       
       echo Publishing the build now ...
       #cd buildScript
       echo $PWD
       # 
       host=https://dev-dash-smoke.multicloud-ibm.com
       token=W-mLy254QkBlmDb9BBUzOh6rit4OFvGPPk6cCsN_ogWAgXZLdhjEXZrAOphzaKv-
       serviceName=urbanDictionary
       providerHref="https://github.com/$REPO"
       duration=$(($ELAPSED/1000000))
       builtat=$(date --utc +%FT%T.%3NZ)
       buildengine="GITACTIONS"
       repourl="https://github.com/$REPO"
       ./buildscript/postBuildsToDI $host $token $serviceName $BUILD_RUNID $providerHref $status $duration $builtat $BUILD_BRANCH $GITHUB_EVENT_NAME $PULL_REQUEST_NUMBER $BUILD_COMMIT $buildengine $GITHUB_SERVER_URL $repourl
    - name: Post Build Failure to DI
      if: ${{ failure() }}
      run: |
       # built_at='2020-01-20T17:42:40Z'
       echo $(date --utc +%FT%T.%3NZ)
       status=Failed
       echo $status
