name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REPO: ${{ github.repository }}
  BUILD_BRANCH: ${{ github.ref }}
  BUILD_COMMIT: ${{ github.sha }}
  BUILD_RUNID: ${{ github.run_id }}
  CI_ENDPOINT_HOSTNAME: $GITHUB_SERVER_URL
  PULL_REQUEST_NUMBER: ${{ github.event.number }}
  BUILD_ENGINE: "GitHub Actions"
  SERVICE_NAME: ${{ github.event.repository.name }}
  
  
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set current date as env variable
      id: startedAt
      run: echo "::set-output name=startedAt::$(date +%s)"
  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Print Custom Env Variables
      run: |

       echo $REPO
       echo $GITHUB_HEAD_REF
       echo $BUILD_BRANCH
       echo $BUILD_COMMIT
       echo $GITHUB_SERVER_URL 
       echo $BUILD_RUNID
       echo $PULL_REQUEST_NUMBER
       echo $GITHUB_EVENT_NAME
    - name: Post Build Success to DI
      if: ${{ success() }}
      run: |
          export STATUS=passed
          startedTime=${{ steps.startedAt.outputs.startedAt }}
          endTime=$(date +%s)
          export ELAPSED=$((endTime-startedTime))

          host="dev-dash-regression2.multicloud-ibm.com"
          token="eAxRRj6dPP6o2ET0gruZC43llecDgS6GY9jzEFuDpUoZJU3hnsKyZqNPcl3lC9q1"
          chmod +x preparebuild.sh
          ./preparebuild.sh $GITHUB_EVENT_NAME $host $token 
          
    - name: Post Build Failure to DI
      if: ${{ failure() }}
      run: |
          export STATUS=failed
          startedTime=${{ steps.startedAt.outputs.startedAt }}
          endTime=$(date +%s)
          export ELAPSED=$((endTime-startedTime))
          
          host="dev-dash-regression2.multicloud-ibm.com"
          token="eAxRRj6dPP6o2ET0gruZC43llecDgS6GY9jzEFuDpUoZJU3hnsKyZqNPcl3lC9q1"
          chmod +x preparebuild.sh
          ./preparebuild.sh $GITHUB_EVENT_NAME $host $token 
